### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by kiner-shah**
PR for #6 
- Added doxyfile, cmakelists.txt
- Minor refactoring

### CODE REVIEW

**Comment by HotelSierraWhiskey** [comment]
Just spent a couple minutes quickly going through this. Looks great. I'll take a closer look as soon as I can. Did you manage to run a compile test with arm-none-eabi-g++?

**Comment by kiner-shah** [comment]
I did compile it with local Linux G++ compiler, compiled fine. Didn't check cross-compiling for ARM since I don't have the right tools for that. Can you please check compiling for ARM both using Makefile and CMake?

**Comment by HotelSierraWhiskey** [comment]
I'll merge this. This project is actually going to be used as a reference for a Rills Automation product prototype sometime next month (namely, for the on-board file system). If you're interested in working on that, let me know as it will be occupying most of my time (I will set up a remote lab with hardware connected. The test mechanism for this project requires access to hardware, so don't worry about it). Thanks for the contribution.

**Comment by kiner-shah** [comment]
Thanks for merging the MR. Yes, I would like to learn more about this repo
and its working. It would be great if you can add some links to
resources related to this project repository (hardware, file system
requirements, goals, etc.).

**Pull request merged**
